version: '3.8'

services:
  # Fabric CA Server
  fabric-ca-server:
    image: hyperledger/fabric-ca:latest
    container_name: fabric-ca-server
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_CA_NAME=localca
    volumes:
      - ./fabric-ca-server-config:/etc/hyperledger/fabric-ca-server
    ports:
      - "7054:7054"
    networks:
      - fabric-network
    command: sh -c "fabric-ca-server start -b admin:adminpwd -d"

  # CouchDB (State Database)
  couchdb:
    image: hyperledger/fabric-couchdb:latest
    container_name: couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpwd
    ports:
      - "5984:5984"
    networks:
      - fabric-network

  # Fabric Peer
  peer:
    image: hyperledger/fabric-peer:latest
    container_name: fabric-peer
    environment:
      - CORE_PEER_ID=peer0.org1
      - CORE_PEER_ADDRESS=peer:7051
      - CORE_PEER_CHAINCODEADDRESS=peer:7052
      - CORE_PEER_CHAINCODELISTENER=peer:7053
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    ports:
      - "7051:7051"
      - "7053:7053"
    volumes:
      - ./peer-config:/etc/hyperledger/fabric
    networks:
      - fabric-network

  # Fabric Orderer
  orderer:
    image: hyperledger/fabric-orderer:latest
    container_name: fabric-orderer
    environment:
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_CLUSTER_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_CLUSTER_LISTENPORT=7051
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_FILELEDGERLOCATION=/var/hyperledger/orderer
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    ports:
      - "7050:7050"
    volumes:
      - ./orderer-config:/var/hyperledger/orderer
    networks:
      - fabric-network

  # Fabric CA Client (For registration/enrollment)
  fabric-ca-client:
    image: hyperledger/fabric-ca-client:latest
    container_name: fabric-ca-client
    depends_on:
      - fabric-ca-server
    networks:
      - fabric-network
    command: sh -c "sleep 5 && fabric-ca-client enroll -u https://admin:adminpwd@fabric-ca-server:7054 --caname localca --tls.certfiles /etc/hyperledger/fabric-ca-server/tls-cert.pem"

networks:
  fabric-network:
    driver: bridge

volumes:
  fabric-ca-server-config:
  peer-config:
  orderer-config:
