# Fabric CA Server Configuration
version: 1.5.5

# Server's listening port (default: 7054)
port: 7054

# CORS Configuration
cors:
  enabled: false
  origins:
    - "*"

# Debug Logging
debug: false

# CRL Size Limit (default: 512000)
crlsizelimit: 512000

# TLS Configuration
tls:
  enabled: true
  certfile: ""
  keyfile: ""
  clientauth:
    type: noclientcert
    certfiles: []

# CA Configuration
ca:
  name: LocalCA
  keyfile: ""
  certfile: ""
  chainfile: ""
  reenrollIgnoreCertExpiry: false

# CRL Configuration
crl:
  expiry: 24h

# Registry Configuration (for authentication and identity attributes)
registry:
  maxenrollments: -1
  identities:
    - name: admin
      pass: adminpw
      type: admin
      affiliation: ""
      attrs:
        hf.Registrar.Roles: "*"
        hf.Registrar.DelegateRoles: "*"
        hf.Revoker: true
        hf.IntermediateCA: true
        hf.GenCRL: true
        hf.Registrar.Attributes: "*"
        hf.AffiliationMgr: true

# Database Configuration (sqlite3, postgres, mysql)
db:
  type: sqlite3
  datasource: fabric-ca-server.db
  tls:
    enabled: false
    certfiles: []
    client:
      certfile: ""
      keyfile: ""

# LDAP Configuration
ldap:
  enabled: false
  url: ldap://<adminDN>:<adminPassword>@<host>:<port>/<base>
  tls:
    certfiles: []
    client:
      certfile: ""
      keyfile: ""
  attribute:
    names: ['uid', 'member']
    converters:
      - name: hf.Revoker
        value: attr("uid") =~ "revoker*"
    maps:
      groups:
        - name: dn1
          value: peer
        - name: dn2
          value: client

# Affiliations Configuration
affiliations:
  org1:
    - department1
    - department2
  org2:
    - department1

# Signing Configuration
signing:
  default:
    usage:
      - digital signature
    expiry: 8760h
  profiles:
    ca:
      usage:
        - cert sign
        - crl sign
      expiry: 43800h
      caconstraint:
        isca: true
        maxpathlen: 0
    tls:
      usage:
        - signing
        - key encipherment
        - server auth
        - client auth
        - key agreement
      expiry: 8760h

# CSR Configuration for Root CA Certificate
csr:
  cn: LocalCA
  keyrequest:
    algo: ecdsa
    size: 256
  names:
    - C: BR
      ST: "Sao Paulo"
      O: IBM
      OU: IBM Consulting
  hosts:
    - MacBook-Pro-de-Andre.local
    - localhost
  ca:
    expiry: 131400h
    pathlength: 1

# Idemix Configuration for Credential Issuance
idemix:
  rhpoolsize: 1000
  nonceexpiration: 15s
  expirednoncecleanup: 15m
